### ISSUE TITLE
how to add subscriber name?

### ISSUE THREAD

**Issue by shairyar** [AhmedSamy/HypeMailchimpBundle#28]
Hi,

Thanks for sharing the bundle, i got it to work just fine, I can get the subscriber added using email however i cant seem to find a way to add subscriber first and last name?

Even your subscribe function does not seem to be taking any names

<pre>
public function subscribe($email_id, $email_type = 'html', $double_optin = true, $update_existing = true, $replace_interests = true, $send_welcome = false, $email_identifier = 'email') {
</pre>

**Comment by luishdez** [comment]
@shairyar 

Use merge bars

```php
<?php

$mca = $this->get('hype_mailchimp');
$mca->getList()
    ->addMerge_vars(
        array(
            'FNAME' => 'Jhon',
            'LNAME' => 'Doe'
        )
    )
    ->subscribe('jhon.doe@gmail.com');
```
