### ISSUE TITLE
Subscriber doesnt subscribe

### ISSUE THREAD

**Issue by VolyaPers** [AhmedSamy/HypeMailchimpBundle#29]
Hi! my code:  
$mc = $this->get('hype_mailchimp');
            $result=$mc->getList()
               ->setListId('49f0e2fed9')
               ->subscribe($freecalc->getEmail());
            exit(var_dump($result));

when I try to add subscribers to the list, the method returns an array. A subscriber is not really added.

**Comment by AhmedSamy** [comment]
can you show the $result array ?

**Comment by VolyaPers** [comment]
I realized that the subscriber's e-mail confirming comes, and while he does not confirm, the program will not add it to the list. What do I need to do to it was added to the database without confirmation? because for this I want to use the api. Someone sends me a request to the site, and should automatically get the list of subscribers

**Comment by VolyaPers** [comment]
problem solved
