### ISSUE TITLE
Is it possible to get api_key?

### ISSUE THREAD

**Issue by ufik** [AhmedSamy/HypeMailchimpBundle#32]
I am creating webhook for mailchimp and I would like to get somehow api_key from this bundle, because it's already defined in config. But it's not possible imho or is it?

**Comment by AhmedSamy** [comment]
there's a parameter array value that holds the config node called `hypemailchimp.config`, you can use it by calling `$container-getParameter('hypemailchimp.config')`

**Comment by ufik** [comment]
I don't think this parameter is accessible outside from your bundle. 

```
You have requested a non-existent service 'hype_mailchimp.config'
```

Maybe it would be nice to have one function, which will verify if given token is correct.

```
public function verifyApiToken($token)
{
    // return bool
}
```

**Comment by AhmedSamy** [comment]
From the error message u got, u are trying to get service not a parameter 

`app/console debug:container --parameters | grep hype_mailchimp`

I can see it there

**Comment by ufik** [comment]
Sorry about that, my bad.
