### ISSUE TITLE
How to set an API key on the fly

### ISSUE THREAD

**Issue by waynobweno** [AhmedSamy/HypeMailchimpBundle#35]
I show that the this feature was added 8 months ago to set the setApikey(), but there is no documentation for it. I have many api keys (many customers) how do I activate that account and then add subscribers to a list in that account? 

where do I put the setApikey()?
       $mc = $this->get('hype_mailchimp');
        $mc->setApikey('xxxxxxxx-us11');
        $data = $mc->getList()
            ->setListId('xxxxxxxx')
            ->subscribe('email@email.com');
        var_dump($data);

**Comment by AhmedSamy** [comment]
yup, that would work
